### ISSUE TITLE
[FEAT] 글쓰기 프래그먼트 화면 전환

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/HARA_AOS#18]
## 🗣️ **Issue**

네비게이션 그래프를 활용하여 글쓰기 프래그먼트 화면 전환 작업을 합니다.

## ✅ **To-do List**

- [x] 글쓰기 프래그먼트 화면 전환
- [x] 각 프래그먼트 별 seekbar 변화
- [x] edittext 입력 시 next 버튼 활성화
- [ ] 선택지 프래그먼트 리사이클러뷰 어댑터 구현
- [x] 각 프래그먼트의 뷰모델 생성
---
- [x] 변경 뷰 반영
