### ISSUE TITLE
[FEAT] 보관함 뷰 로직 짜기

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/HARA_AOS#20]
## ✅ **To-do List**

- [x]  '1초만에 고민 해결하기' 버튼 누르면 액티비티로 연결
- [x] 서버통신에 따라서 어떤 (리사이클러뷰)아이템에 '고민중/고민해결'이 뜰지를 정해두기
visibility를 주거나 OR 바인딩 어댑터/코드로 색깔+텍스트 변경하기(준우는 바인딩 어댑터 쓴다)
- [x] 토글 버튼 눌렀을 때 고민중↔고민 해결로 바뀌게 == 토글 버튼으로 처리하기
- [x] 편집이라고 텍스트뷰 만 달아놓기. 삭제는 없어졌으니까 신경 안 써도 돼.
- [x] 탭 스와이프 했을 때 '혼자 고민 ↔ 함께 고민' 바뀌게
