### ISSUE TITLE
[FEAT] Apply Hilt / SeverConnection

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#25]
## 🗣️ **Issue**

- Hilt 적용
- 서버통신을 위한 기초 세팅

## ✅ **To-do List**

- [x] Add Hilt Annotation
- [x] Add Retorit
- [x] Write DI Module
- [x] Add Test ServerConnection
