### ISSUE TITLE
[FEAT] 프로젝트 환경 설정

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#3]
## 🗣️ **Issue**
- 프로젝트 기초 세팅 후 환경설정을 할 예정입니다. 또한 Cradle Bottom Navigation 도 작업할 예정입니다.
![Untitled](https://user-images.githubusercontent.com/70648111/210092920-eed911f2-05e5-4d4f-b420-d6616beac643.png)

## ✅ **To-do List**

- [x]  Util Class
- [x] Binding Class
- [x] 기능별 Package 구분
- [x] Cradle 바텀네비게이션 
- [x] Navigation Graph
- [x] 디자인 가이드에 따른 Color 추가
- [x] 디자인 가이드에 따른 font 추가
- [x] 디자인 가이드에 따른 Style 추가
- [ ] 앱 아이콘 변경
