### ISSUE TITLE
[FEAT] 글쓰기 선택지 리싸이클러뷰 로직 / 바텀시트 연결

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#32]
## 🗣️ **Issue**
글쓰기 선택지 리싸이클러뷰 로직과 바텀시트를 연결하여 뷰모델 연동까지 완료 할 예정입니다.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/70648111/211263291-ef80e73f-039f-4c76-b91f-ac314385a89c.png"> <img width="324" alt="image" src="https://user-images.githubusercontent.com/70648111/211263360-4765ac4a-10be-474b-9325-9fa9b445c646.png">

## ✅ **To-do List**

- [x] 선택지 리싸이클러뷰
- [x] 바텀시트 연결
- [x] 바텀시트 완료 후 뷰모델에 연동
- [x] 전체 뷰모델 연동
- [x] 글쓰기 흐름 연결
- [x] 스와이프제스처
- [x] 화면전환 애니메이션
