### ISSUE TITLE
[FEAT] 보관함 서버 연결

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/HARA_AOS#36]
## 🗣️ **Issue**

보관함 프래그먼트의 GET 서버 통신을 구현합니다.

## ✅ **To-do List**

- [x]  함께 고민 목록 조회 GET
- [x] 함께 고민 정렬 (결정중, 결정완료)
- [x]  혼자 고민 목록 조회 GET
- [x] 혼자 고민 정렬 (결정중, 결정완료)
