### ISSUE TITLE
[FEAT] 홈 fragment : 함께해라 글 목록 서버통신

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/HARA_AOS#37]
## 🗣️ **Issue**
**홈 activity - 홈 fragment - 함께해라 탭 : 고민글 전체조회**
서버에 카테고리 ID 를 parameter 로 붙여 쿼리로 보내고
고민글 목록을 받아 화면에 보여주는 서버통신을 수행합니다.

**이후 상의/고민해야 하는 부분**
- [ ] AllPostResDto에서 img는 String 타입으로 받았습니다
- [ ] TogetherFragment에서 comment로
[1]이라고 적힌 건 카테고리 recycler view, [2]라고 적힌 건 글 목록 recycler view 관련
로직입니다
- [ ] recycler view2 - 아이템마다 선택된 option의 값을 저장해야 할 듯

## ✅ **To-do List**
- [ ]  서버통신

## 🚀 버튼 로직 : 분기 처리 고민

**[ 사용한 변수 ]**

**A. optClickable**
옵션이 클릭 가능해야 하는가?
item_post.xml - itOptClickable
layout_post_option.xml - layOptClickable

**B. myPost**
체크 버튼이 보이는가? & 최종결정/투표하기 어떤 버튼이 보이는가?
item_post.xml - itMyPost
layout_post_option.xml - layMyPost

**C. optSelNum**
옵션에 어떤 체크 모양이 보이는가?
item_post.xml - itOptSelNum
layout_post_option.xml - layOptSelNum

**D. optSel**
(한 글/아이템에서) 지금 선택 중인 옵션이 이 옵션 맞니?
layout_post_option.xml - layOptSel (bool)

**E. voteOptSel**
(한 글/아이템에서) 최종 선택한 옵션이 이 옵션 맞니?
item_post.xml - itVoteOptSel (int)
layout_post_option.xml - layVoteOptSel (bool)

**[ 분기처리 고민 ]**

A. 내가 쓴 글인가 (if: isAuthor)
- [ ] 옵션 clickable = false <optClickable>
- [ ] 옵션 img(check) - visibility : gone <myPost>
- [ ] '최종결정 하러가기' 버튼 visible / '투표하기' 버튼 invisible <myPost>

B. 남이 쓴 글인가 (else)
- [ ] 옵션 img(check) - visibility : visible <myPost>
- [ ] '최종결정 하러가기' 버튼 invisible / '투표하기' 버튼 visible <myPost>

B-a) 투표 함 (if: isVoted == false)
- [ ] 옵션 clickable = false <optClickable>
- [ ] 옵션 img(check) - src : 단순 체크 <OptSelNum == -1>

B-b) 투표 아직 안 함 (else)
- [ ] 옵션 clickable = true <optClickable>
- [ ] 옵션 img(check) src : check_on <OptSelNum == 0 -> 1~4로 바뀜>
** 이때 투표하기 버튼 누르면? 2-1 로직을 타야 겠지?

item_post.xml에서
optSelNum이
-1 -> [투표 함] 투표 완료!
0 -> [투표 안함] 옵션이 선택 안 됨 = 투표하기 흰배경
1 2 3 4 -> [투표 안함] 옵션이 선택됨 = 투표하기 주황배경

** optSelNum에 따라
투표하기 버튼 & 옵션의 스타일이 바뀐다

** 버튼이 enable? 옵션이 clickable?
