### ISSUE TITLE
[FEAT] CI 구축 및 Slack 연동

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#4]
## 🗣️ **Issue**

Main Branch로 머지전 Git Action을 활용한 빌드 검사를 위해 CI를 구축합니다

## ✅ **To-do List**

- [x]  GitAction 
- [x] Add Secret for local properties
- [x]  Write yml files
- [x] Connect Slack with WEBHOOK_URL
