### ISSUE TITLE
[FEAT] 최종 결정 PATCH 통신 준비 및 상세화면 뷰 분리

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/HARA_AOS#44]
## 🗣️ **Issue**

혼자/함께 최종 결정 액티비티에서 PATCH 통신 로직을 작업합니다.

## ✅ **To-do List**

- [x]  혼자 고민 최종 결정 PATCH 통신 진행
- [x]  함께 고민 최종 결정 PATCH 통신 진행
- [x] 고민글 상세화면 뷰 분리(함께/혼자)
