### ISSUE TITLE
[FEAT] 게시물 작성 서버통신 / 홈화면 동작

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#45]
## 🗣️ **Issue**

글쓰기 뷰에서 혼자/함께 고민글을 게시하는 서버통신을 하려고 합니다. 

## ✅ **To-do List**

- [x] Post /worry/alone
- [x] Post /worry/with
- [x] Reqres 서버통신 삭제
- [x] 함께해라 클릭하면: 맨위로
- [x] 뒤로가기 문제(애니메이션, seek bar)
- [x] 홈화면 스와이프 리프레시
- [x] 같은/다른카테고리 누르면 맨위로 스크롤
- [x] 디자인 변경사항 반영
- [x] 바텀네비게이션 가운데 버튼 터치 방지
