### ISSUE TITLE
[FEAT] 보관함&상세보기의 최종 결정 화면 연결 로직 구현

### ISSUE THREAD

**Issue by wkdyujin** [TeamHARA/HARA_AOS#47]
## 🗣️ **Issue**

보관함 및 상세보기의 최종 결정 화면 연결 로직을 구현합니다.

## ✅ **To-do List**

- [x]  보관함(혼자/함께) 아이템 클릭 시 상세보기 액티비티 전환
- [x] 상세보기 액티비티에서 최종 결정 액티비티 전환
- [x] Patch 통신 로직 구현
