### ISSUE TITLE
[FEAT/UI] 상세화면 뷰 구성 및 서버통신

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#53]
## 🗣️ **Issue**
상세화면을 혼자고민/함께고민 상세화면 뷰 구성과 GET 구성

## ✅ **To-do List**

- [x] 함께고민 , 혼자고민 상세화면 
- [x] 혼자고민 GET 통신
- [x] 함께고민 GET 통신
- [x] 바텀시트 다이얼로그 추가
- [x] 홈 서버통신 오류 수정
