### ISSUE TITLE
[FEAT/UI] 보관함 프래그먼트 화면 구성

### ISSUE THREAD

**Issue by skylartosf** [TeamHARA/HARA_AOS#7]
## 🗣️ **Issue**

함께해라 프래그먼트 화면 구성 요소에 대하여 작업합니다.

## ✅ **To-do List**

- [x]  '1초 만에 고민 해결하러 가기' 카드 뷰
- [x] 혼자 고민/함께 고민 탭바? 뷰페이저?
- [x] 고민중/고민 해결 정렬 필터?
- [x] 리사이클러 뷰 : 고민 목록 보여주기
