### ISSUE TITLE
[Chore] Dto 최적화 및 Intent 변경

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#72]
## 🗣️ **Issue**
임시로 작성했던 로직을 개선할 예정입니다.

## ✅ **To-do List**

- [x] 일부 DTO 최적화
- [x] 고민완료 상태이면 앱바 타이틀 변경
- [x] 인텐트 전달 최적화 
- [x] 더미이미지 삽입
- [x] 카테고리에 콘텐트 
- [x] 업로드 버튼 활성화때도 비활성화
- [x] 오탈자 수정
