### ISSUE TITLE
[REFACTOR] 시연용 코드 리팩토링 및 개선

### ISSUE THREAD

**Issue by IslandofDream** [TeamHARA/HARA_AOS#78]
## 🗣️ **Issue**
임시 코드 / 시연용 코드들의 리팩토링 및 개선을 진행할 예정입니다.

## ✅ **To-do List**

- [x]  토글버튼 리스너
- [x]  상세화면 게시물 시연코드 삭제
- [x] 스플래시 화면 개선
- [x] 멘토링 피드백 적용 (Reponse 제거, 하위호환성,  SerialName)
- [x] API 레포짓토리 분리(함께,혼자 API)

**Comment by IslandofDream** [comment]
공통
* 로딩 상태에 대한 UI 처리 (버튼을 눌렀을 때 비동기 처리 등)
* 디펜던시를 잘 관리할 수 있는 방법에 대해 생각해보기

[해라]
https://github.com/TeamHARA/HARA_AOS
* Request, Response @Serializable 은 항상 SerialName 과 사용되어야 함 (minifyWithR8 과정에서 난독화 되어 Proguard 이슈 발생) -> 실제로 배포 해보길 희망
* Kotlin official convention 도입하면 좋을듯(변수명이 파스칼인 경우 존재) -> 이런 부분은 lint 나 제공되는 것을 활용해서 시간을 아끼자
* Hilt binds 활용 굳
* HARARepository 에는 Response 로 감싸여 있을 필요가 없을 것 같음 body() 로 굳이 찾을 필요 없어보임
* Navigation Component 활용 굳!
* Color, Drawable 등의 리소스를 처리할 떄는 하위호환성을 챙겨야 됨
* Theme 가 정의 되어 있고 재활용하려는 모습이 좋았음
